# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):

        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.label_2 = QtWidgets.QLabel(Form)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_5 = QtWidgets.QLabel(Form)
        self.textBrowser_player = QtWidgets.QTextBrowser(Form)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.label_timer = QtWidgets.QLabel(Form)
        self.QLCDTimer = QtWidgets.QLCDNumber(Form)
        self.label = QtWidgets.QLabel(Form)
        self.label_4 = QtWidgets.QLabel(Form)
        self.textBrowser_bot = QtWidgets.QTextBrowser(Form)
        self.label_3 = QtWidgets.QLabel(Form)
        self.textBrowser_log = QtWidgets.QTextBrowser(Form)
        self.QLCDBarrel = QtWidgets.QLCDNumber(Form)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)

        Form.setObjectName("Form")
        Form.resize(640, 480)

        self.gridLayout_4.setObjectName("gridLayout_4")

        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)

        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 1, 1, 1)

        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 2, 1, 1)

        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 1, 1, 1)

        self.textBrowser_player.setObjectName("textBrowser_player")
        self.gridLayout_4.addWidget(self.textBrowser_player, 2, 0, 3, 1)

        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 2, 1, 1, 1)

        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_4.addWidget(self.textBrowser, 2, 2, 3, 1)

        self.label_timer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_timer.setObjectName("label_timer")
        self.gridLayout_4.addWidget(self.label_timer, 3, 1, 1, 1)

        self.QLCDTimer.setObjectName("QLCDTimer")
        self.gridLayout_4.addWidget(self.QLCDTimer, 4, 1, 1, 1)

        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 5, 0, 1, 1)

        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 5, 2, 1, 1)

        self.textBrowser_bot.setObjectName("textBrowser_bot")
        self.gridLayout_4.addWidget(self.textBrowser_bot, 6, 0, 3, 1)

        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 6, 1, 1, 1)

        self.textBrowser_log.setObjectName("textBrowser_log")
        self.gridLayout_4.addWidget(self.textBrowser_log, 6, 2, 3, 1)

        self.QLCDBarrel.setObjectName("QLCDBarrel")
        self.gridLayout_4.addWidget(self.QLCDBarrel, 7, 1, 1, 1)

        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.No | QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_4.addWidget(self.buttonBox, 8, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Game_Loto"))
        self.label_2.setText(_translate("Form", "Player"))
        self.pushButton.setText(_translate("Form", "Start Game"))
        self.label_6.setText(_translate("Form", "Best players Stat"))
        self.label_5.setText(_translate("Form", "Your name"))
        self.label_timer.setText(_translate("Form", "Total Timer"))
        self.label.setText(_translate("Form", "Bot"))
        self.label_4.setText(_translate("Form", "Game_Log"))
        self.label_3.setText(_translate("Form", "Barrel"))
